### ISSUE TITLE
Feature: User can search

### ISSUE THREAD

**Issue by chrisahn1** [chrisahn1/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
User may enter a fish name and click on the search button. If the name is found, then the view list displays all available results. If not results have been found, the list will display no results().

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Create a header that has name of the webpage, Fish Management
- [ ] Add buttons View Saved List and Search at the right side
- [ ] Below the header, add a text input and a search button on the right side. Make sure the text input is required.
- [ ] Add a text display on the right side of the search button that displays the search results
- [ ] Add a background image below the search bar and make it fixed position.
- [ ] In the main.js file, console log the results when the search button is clicked since our goal is to check if the search feature is working properly. The name of the fish must match the object property of fish name.
- [ ] Make sure to display the following properties for each fish: Image Gallery, Species Name, Scientific Name, Population, Population Status, Location, Harvest Type, Total Fat, Carbohydrates, Calories, Cholesterol, Protein, Environmental Concerns, and Environmental Effects.
- [ ] For Image Gallery, access the src and alt.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
