### ISSUE TITLE
User can click on nutrition to view nutrition modal

### ISSUE THREAD

**Issue by chrisahn1** [chrisahn1/ajax-project#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
When the user clicks on the nutrition clickable, a modal displays the nutritional value of the fish.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/22688744/157783063-48c5cafd-b90e-435a-84ff-7d56f64b08b9.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] When the user clicks on the nutritional clickable, a white box modal appears.
- [x] You may include as many nutritional facts in the box modal but make sure to have them in columns(nutrition and value)
- [x] Have the background darker when the box modal appears and disabled.
- [x] For an exit, you may include either an exit button below or the user may click outside of the box modal.
- [x] When the box modal exits, it disappears and everything comes back to normal and abled.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
