### ISSUE TITLE
User can click on the gallery button to view photos and have the android version

### ISSUE THREAD

**Issue by chrisahn1** [chrisahn1/ajax-project#14]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user clicks on the gallery button, a modal will show and display a photo gallery.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Android 1 and 2](https://user-images.githubusercontent.com/22688744/160278461-bbe20bd8-bc3f-439d-bf86-fd5eccdfe649.png)
![Android 3 and 4](https://user-images.githubusercontent.com/22688744/160278463-53442034-2670-49c6-8f07-21d6b539886a.png)
![Desktop 1 and 2](https://user-images.githubusercontent.com/22688744/160278465-7d223d91-bce7-4515-9259-9be0d893d1dd.png)
![Desktop 3 and 4](https://user-images.githubusercontent.com/22688744/160278467-7ad084cd-53ae-4134-95bc-f70fe5e10217.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Have the gallery button next to the nutrition button on the right
- [x] Make sure the dom creation uses the data entry storage that was saved from the api image gallery.
- [x] When the gallery button is clicked, a shadow is the background with everything else disabled besides the modal.
- [x] Have an exit button that will close the modal and everything is abled.
- [x] Make sure the photos fit in the modal well.
- [x] According to the wireframe, have them rearranged to fit appropriately to the android version.
- [x] If the search button is clicked an no results show up, display a 'no results were found' message in the container.
- [x] Check that your desktop and android versions resemble the estimates of the wireframes as much as possible.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
