### ISSUE TITLE
User can view search results

### ISSUE THREAD

**Issue by chrisahn1** [chrisahn1/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user clicks on the search button after typing the species name, the view page displays all available search results showing the information about each fish.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://user-images.githubusercontent.com/22688744/156074598-d3835d49-2a69-4ffe-a065-def17d77fbc7.png)
![image](https://user-images.githubusercontent.com/22688744/156074661-1cc98eb1-e68a-416d-a674-da23aff061e8.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [ ] Add a sibling `div[data-view="entries"]` to the HTML.
- [ ] Add an empty unordered list to the `div[data-view="entries"]` element in the HTML.
- [ ] Add some dummy journal entries to the unordered list in the HTML and style them to match the wireframe.
- [ ] Create a frame that will be used for displaying the fish image and the information of each fish. Make sure the frame is transparent.
- [ ] Divide the properties into a total of 5 columns as displayed from the wireframe images. Hint: use dom tree creation for each frame.
- [ ] Each search result should have an add button on the bottom right hand corner.
- [ ] Make sure it fits for desktop and phone
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
