### ISSUE TITLE
User can view added list

### ISSUE THREAD

**Issue by chrisahn1** [chrisahn1/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user may view all the fish species that is in the added list.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/22688744/156076152-9e939ab9-69f2-400c-b454-98466bf225db.png)
![image](https://user-images.githubusercontent.com/22688744/156076211-4aaaa5dc-3eab-48be-a74a-76e9c2d84fc7.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [ ] Add a `div[data-view="view-saved-form"]` to the HTML.
- [ ] When the add button is clicked, remove the added fish from the search results page.
- [ ] The added fish should unshift to the local storage.
- [ ] When the View Save List Button is clicked, the page switches to the View Added List Page which displays all added fish.
- [ ] The displays of fish information is the same as the view page. 
- [ ] On the bottom right corner of each saved fish, create a circle that will eventually be used for a click function.
- [ ] Verify that new entries are saved to local storage along with the rest of the data model on page reload.
- [ ] Make sure the display fits for desktop and phone.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
