### ISSUE TITLE
User can sort added list by sustainability and alphabetical order

### ISSUE THREAD

**Issue by chrisahn1** [chrisahn1/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the Sort button is clicked, the saved results are sorted based on alphabetical order.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] When the sort link is clicked, the view saved list page must organize the fish based on alphabetical order.
- [ ] Remove the entire tree.
- [ ] Sort the local storage array that holds the fish data.
- [ ] You may use any of the sorting algorithms such as quicksort, mergesort, and heapsort.
- [ ] Once the sorting is complete, display the sorted array into the unordered list tree.
- [ ] Make sure it displays for desktop and phone
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
