### ISSUE TITLE
User can delete entry from added list

### ISSUE THREAD

**Issue by chrisahn1** [chrisahn1/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user may delete an entry from the view saved list page

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/22688744/156077781-6a1a4563-7f83-4f3d-913e-8109ae1c9066.png)
![image](https://user-images.githubusercontent.com/22688744/156077840-ecad6ab5-9d4f-43f5-ab79-b1867610e74b.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] When the user clicks on the circle in the bottom right corner of the frame, the circle lights up and shows a check mark to signify it's been selected. As many circles may be selected at the same time. Make sure the page doesn't refresh.
- [ ] When the user clicks on Delete Selected, the page removes the selected fish.
- [ ] Make sure to update the local storage.
- [ ] If the user clicks on Delete All, a modal shows up.
- [ ] When the modal shows up, it appears as a white box modal with a question and the two buttons at the bottom, Cancel and Confirm.
- [ ] Everything behind the box modal must be transparent and everything disabled except for the box modal.
- [ ] If the user clicks on Cancel, the box modal disappears and the features are enabled.
- [ ] If the user clicks on Confirm, remove the entire tree.
- [ ] Make sure the update the local storage which will be empty.
- [ ] Make sure it fits for desktop and phone.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
