### ISSUE TITLE
User can search

### ISSUE THREAD

**Issue by chrisahn1** [chrisahn1/ajax-project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can enter a keyword and click on the search button to display results.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/22688744/157778746-5aca1b8f-9c80-41da-80ea-41933f0a6b67.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a header that contains the text input 
- [x] Next to the text input, create a search button
- [x] In the main.js file, write the xhr code to get the API
- [x] Create the function when the search button is clicked.
- [x] Within the function where the button is clicked, display the fish species image and name. You may wish to display other fields just for testing.
- [x] The display does not have to look exactly as the display fish in the wireframe image but as long as it shows the output correctly.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
