### ISSUE TITLE
User can view search results

### ISSUE THREAD

**Issue by chrisahn1** [chrisahn1/ajax-project#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Now that the search button display works, display the results in a responsive layout fashion.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/22688744/157779436-20cc6ec5-4548-497d-82f8-b9818efd64df.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a ul tree by using a function that will create the dom.
- [x] Have each box contain the fish image and name centered
- [x] Have the fish species organized with 3 in a row.
- [x] have the header in a fixed position.
- [x] Fix the remaining header.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
