### ISSUE TITLE
User can click on one of the results and views the info of the fish

### ISSUE THREAD

**Issue by chrisahn1** [chrisahn1/ajax-project#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
When the user clicks on a fish species box, the page goes to it's info page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![wireframe](https://user-images.githubusercontent.com/22688744/159274648-b1755080-6420-43a9-b507-3e178c39ed8e.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] When a fish is hovered, create a timed animation where its size increased enough where it doesn't cover up other fish.
- [x] When a fish is clicked, the page changes to the info page of the fish being clicked.
- [x] Add the fish species name, scientific name, and image as displayed in the wireframe.
- [x] Add a clickable nutrition that will eventually be the modal.
- [x] Add the description based on one of the object fields.
- [x] Add any 4 fields of your choice in the first and second box areas each.
- [x] Lastly, add 4 fields of your choice below that will be scroll downs eventually.
- [x] When the user enters a new search input, change the page to the list of fish species. If the user enters another input, it should change to a new search result, removing the previous search result.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
